# Generated by Django 4.0.4 on 2023-09-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AttSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='myclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AttSystem.class'),
        ),
    ]
