# Generated by Django 4.0.4 on 2023-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttSystem', '0004_userprofile_semester_course_student_mycourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='myclass',
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(to='AttSystem.student'),
        ),
    ]
