# Generated by Django 4.0.4 on 2023-10-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttSystem', '0005_remove_student_myclass_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='myclass',
            field=models.ManyToManyField(related_name='myclass', to='AttSystem.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(related_name='student', to='AttSystem.student'),
        ),
    ]
